CREATE TABLE IF NOT EXISTS users (
    user_id TEXT PRIMARY KEY NOT NULL,
    username TEXT NOT NULL,
    permission INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS semesters (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    start DATE NOT NULL,
    end DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS courses (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(100) NOT NULL,
    ename VARCHAR(200) NOT NULL,
    code VARCHAR(20) NOT NULL,
    tea_id VARCHAR(10) NOT NULL,
    tea_name VARCHAR(50) NOT NULL,
    intro TEXT NOT NULL,
    mailbox VARCHAR(200) NOT NULL,
    term INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS labrooms (
    id integer PRIMARY KEY AUTOINCREMENT,
    room VARCHAR(10) NOT NULL,
    name VARCHAR(30) NOT NULL,
    manager VARCHAR(10) NOT NULL
);
